# Generated by Django 2.2 on 2019-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=20)),
                ('body', models.TextField(max_length=1000)),
                ('cc', models.BooleanField(default=False)),
                ('bcc', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField()),
            ],
        ),
    ]
